### ISSUE TITLE
Can NOT run "npm install" or "npm run watch"

### ISSUE THREAD

**Issue by As3ad10** [uilibrary/Stocky-Issues-and-Feature-request#109]
Hi, 
when I run <code> npm run watch</code> I keep getting a punch of errors 
Here are the errors

> @ watch C:\Users\As3ad\Desktop\techamend\Al-Faqih\Stocky-Ultimate-inventory-with-pos
> npm run development -- --watch

> @ development C:\Users\As3ad\Desktop\techamend\Al-Faqih\Stocky-Ultimate-inventory-with-pos
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

The system cannot find the path specified.
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\webpack\bin\webpack.js ENOENT
    at notFoundError (C:\Users\As3ad\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\As3ad\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\As3ad\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.cp.emit (C:\Users\As3ad\AppData\Roaming\npm\node_modules\cross-env\node_modules\cross-spawn\lib\enoent.js:30:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node_modules\\webpack\\bin\\webpack.js',
  path: 'node_modules\\webpack\\bin\\webpack.js',
  spawnargs: [
    '--progress',
    '--hide-modules',
    '--config=node_modules/laravel-mix/setup/webpack.config.js',
    '--watch'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\As3ad\AppData\Roaming\npm-cache\_logs\2021-05-24T17_47_50_089Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `npm run development -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\As3ad\AppData\Roaming\npm-cache\_logs\2021-05-24T17_47_50_245Z-debug.log

my npm version is <code>6.14.5</code>
my node version is <code>v14.5.0</code>

I have also attached the log file

Regards,

[2021-05-24T17_47_50_245Z-debug.log](https://github.com/uilibrary/Stocky-Issues-and-Feature-request/files/6534111/2021-05-24T17_47_50_245Z-debug.log)

**Comment by hamzakifani** [comment]
it will help you  https://stackoverflow.com/questions/39190164/npm-the-system-cannot-find-the-path-specified
