### ISSUE TITLE
npm run development failed with error

### ISSUE THREAD

**Issue by kapil019** [uilibrary/Stocky-Issues-and-Feature-request#339]
npm run development failed with error
```
ERROR in ./resources/src/assets/styles/sass/themes/lite-purple.scss (./node_modules/css-loader!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./resources/src/assets/styles/sass/themes/lite-purple.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "../globals/globals.scss";
       ^
      It's not clear which file to import. Found:
  resources/src/assets/styles/sass/globals/_globals.scss
  resources/src/assets/styles/sass/globals/globals.scss
   ╷
97 │ @import "../globals/globals.scss";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  stdin 97:9  root stylesheet
      in Stocky_3.6.0/resources/src/assets/styles/sass/themes/lite-purple.scss (line 97, column 9)
 @ ./resources/src/assets/styles/sass/themes/lite-purple.scss 2:14-232
 @ ./resources/src/login.js
 @ multi ./resources/src/login.js
```

**Comment by naime-hossain** [comment]
Please delete resources/src/assets/styles/sass/globals/globals.scss file and and run again . thank you

**Comment by kapil019** [comment]
Now this kind of errors are there

```
ERROR in ./resources/src/views/app/pages/pos.vue?vue&type=style&index=0&lang=css& (./node_modules/style-loader/dist/cjs.js!./node_modules/css-loader??ref--6-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--6-2!./node_modules/vue-loader/lib??vue-loader-options!./resources/src/views/app/pages/pos.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (Stocky_3.6.0/node_modules/style-loader/dist/index.js:19:24)
 @ ./resources/src/views/app/pages/pos.vue?vue&type=style&index=0&lang=css& 1:0-378 1:0-378
 @ ./resources/src/views/app/pages/pos.vue
 @ ./resources/src/router.js
 @ ./resources/src/main.js
 @ multi ./resources/src/main.js ./resources/src/assets/styles/sass/globals/globals.scss

ERROR in ./node_modules/swiper/dist/css/swiper.css
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (Stocky_3.6.0/node_modules/style-loader/dist/index.js:19:24)
 @ ./node_modules/vue-image-lightbox-carousel/src/components/VueImageLightboxCarousel.vue?vue&type=script&lang=js& (./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-image-lightbox-carousel/src/components/VueImageLightboxCarousel.vue?vue&type=script&lang=js&) 62:0-35
 @ ./node_modules/vue-image-lightbox-carousel/src/components/VueImageLightboxCarousel.vue?vue&type=script&lang=js&
 @ ./node_modules/vue-image-lightbox-carousel/src/components/VueImageLightboxCarousel.vue
 @ ./node_modules/vue-image-lightbox-carousel/src/main.js
 @ ./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-upload-multiple-image/src/components/VueUploadMultipleImage.vue?vue&type=script&lang=js&
 @ ./node_modules/vue-upload-multiple-image/src/components/VueUploadMultipleImage.vue?vue&type=script&lang=js&
 @ ./node_modules/vue-upload-multiple-image/src/components/VueUploadMultipleImage.vue
 @ ./node_modules/vue-upload-multiple-image/src/main.js
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/src/views/app/pages/products/Add_product.vue?vue&type=script&lang=js&
 @ ./resources/src/views/app/pages/products/Add_product.vue?vue&type=script&lang=js&
 @ ./resources/src/views/app/pages/products/Add_product.vue
 @ ./resources/src/router.js
 @ ./resources/src/main.js
 @ multi ./resources/src/main.js ./resources/src/assets/styles/sass/globals/globals.scss

ERROR in ./node_modules/@trevoreyre/autocomplete-vue/dist/style.css
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (Stocky_3.6.0/node_modules/style-loader/dist/index.js:19:24)
 @ ./resources/src/main.js 76:0-53
 @ multi ./resources/src/main.js ./resources/src/assets/styles/sass/globals/globals.scss

ERROR in ./node_modules/vue-select/dist/vue-select.css
Module build failed (from ./node_modules/style-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (Stocky_3.6.0/node_modules/style-loader/dist/index.js:19:24)
 @ ./resources/src/main.js 74:0-40
 @ multi ./resources/src/main.js ./resources/src/assets/styles/sass/globals/globals.scss


```

**Comment by kapil019** [comment]
Hi @naime-hossain Can you please help

**Comment by naime-hossain** [comment]
did you add something or some CSS library ?

**Comment by naime-hossain** [comment]
and remove /resources/src/assets/styles/sass/globals/globals.scss not /resources/src/assets/styles/sass/globals/_globals.scss

**Comment by kapil019** [comment]
I have not added anything in CSS Library, 
And removed only /resources/src/assets/styles/sass/globals/globals.scss

not working,

**Comment by naime-hossain** [comment]
![image](https://user-images.githubusercontent.com/12586039/131217885-ea99cd21-f19a-4403-8bbc-1e037a2abc64.png)
i think you did not remove the file

**Comment by kapil019** [comment]
I removed , and this is generating again while runing
npm run development command 
And throwing error again and again even removing file before development command

**Comment by naime-hossain** [comment]
Please start with New stocky code base and check

**Comment by kapil019** [comment]
Thanks @naime-hossain working

**Comment by naime-hossain** [comment]
> Thanks @naime-hossain working

Welcome and if you like our work & support, you can leave a review that will motivate our team toward further development if possible. If you don’t know how to provide ratings & review please visit this link: https://help.market.envato.com/hc/en-us/articles/203269490-Giving-Feedback-On-Items thank you :)
