### ISSUE TITLE
Issue while running Nom run prod

### ISSUE THREAD

**Issue by MnlLBD1** [uilibrary/Stocky-Issues-and-Feature-request#436]
Hello , after doing what you said , here is the errors I get, can you help me please ? 

> @ prod /home/techunuy/stock-app.techaccio.com
> npm run production

/home/techunuy/stock-app.techaccio.com/node_modules/npm/lib/cli.js:2
module.exports = async process => {
                       ^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/techunuy/stock-app.techaccio.com/node_modules/npm/bin/npm-cli.js:2:1)
    at Module._compile (module.js:541:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/techunuy/.npm/_logs/2021-12-22T14_20_41_836Z-debug.log

**Comment by MnlLBD1** [comment]
I know I have tried it but it doesn't work .. can you please verify the updates we have done in the front and tell us if it is good, and if you can do some tasks for our company we can pay you

**Comment by hamzakifani** [comment]
Please contact via : uilib.help@gmail.com with your cpanel + app access + your modifications. Thank you

**Comment by MnlLBD1** [comment]
tHANK YOU
